### ISSUE TITLE
The old "Z" way of placing on top of things

### ISSUE THREAD

**Issue by Matusz27** [Xpazeman/tld-placing-anywhere#1]
I am missing the Z button way of placing things on top of each other, why was it removed, and could it be brought back? I really miss it especially when placing towers of the newspapers when I have to manually get it up and up and up

**Comment by Xpazeman** [comment]
TLD switched the Unity version, and that broke the Input module so controls had to be reworkd from scratch.
New version is coming soon with the option added back as a toggle, along with key tooltips.
